name: Web Browser Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tk
    - name: Clone tests
      uses: actions/checkout@v2
      with:
        repository: utah-cs4962-fa21/tests
        path: tests
    - name: Run tests
      run: |
        ./tests/src/run-tests.py
